# Get all accounts
GET http://localhost:3003/accounts
Content-Type: application/json

###

# Get account balance
GET http://localhost:3003/account/balance?cpf=23456789123
Content-Type: application/json

###

# Add new account
POST http://localhost:3003/accounts
Content-Type: application/json

{
    "name":"Mia",
    "cpf": 234567891231,
    "birthdate": "2003/11/08"
}

###

# Add a deposit to transactions history
PUT http://localhost:3003/account
Content-Type: application/json

{
    "name":"Maria",
    "cpf":12345678901,
    "amount": 1000
}

###

# Add a debt to transactions history
PUT http://localhost:3003/account/pay
Content-Type: application/json

{
    "date": "2022-11-11",
    "description": "Credit Card",
    "amount": -1000, 
    "cpf":12345678901
}

###

# Update account balance according to transactions history
PUT http://localhost:3003/account/update-balance
Content-Type: application/json

{
    "cpf":12345678901
}

###

# Add transfer between accounts to transactions history
POST http://localhost:3003/transfer
Content-Type: application/json

{
    "senderName":"Maria",
    "senderCpf":12345678901,
    "recipientName":"Belle",
    "recipientCpf":23456789123,
    "amount":1000
}
