GET http://localhost:3003/users
Content-Type: application/json

###

POST http://localhost:3003/users
Content-Type: application/json

{
    "name":"Jonas",
    "cpf": 234567891231,
    "birthdate": "2003/11/08"
}

###

GET http://localhost:3003/user/balance?cpf=23456789123
Content-Type: application/json

###
PUT http://localhost:3003/user
Content-Type: application/json

{
    "name":"Maria",
    "cpf":12345678901,
    "amount": 1000
}

###

PUT http://localhost:3003/user/pay
Content-Type: application/json

{
    "date": "2022-12-25",
    "description": "Credit Card",
    "amount": 500, 
    "cpf":12345678901
}

###

PUT http://localhost:3003/user/update-balance
Content-Type: application/json

{
    "cpf":23456789123
}